# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-24 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='date_requested',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
