# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-31 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_requester'),
    ]

    operations = [
        migrations.AddField(
            model_name='requester',
            name='assigned_authoriser',
            field=models.IntegerField(blank=True, choices=[(2, 'name1')], null=True),
        ),
    ]
