# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-04 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20171104_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='user',
            field=models.CharField(default='', max_length=20),
        ),
    ]
