# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-31 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_requester_assigned_authoriser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requester',
            name='assigned_authoriser',
            field=models.IntegerField(blank=True, choices=[(2, 'name1'), (6, 'name4'), (7, 'name5'), (10, 'test7'), (11, 'test8'), (14, '')], null=True),
        ),
    ]
