# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-05 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20171104_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='requests',
            name='start',
            field=models.DateField(),
        ),
    ]
