# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-11 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180210_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='comment',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
