# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-05 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20171105_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='leave_type',
            field=models.CharField(choices=[('Holiday', 'Holiday'), ('Holiday', 'Sick Leave')], default='Holiday', max_length=10),
        ),
    ]
