# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-11 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180211_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
