# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20171105_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='leave_type',
            field=models.CharField(choices=[('Holiday', 'Holiday'), ('Sick Leave', 'Sick Leave')], default='Holiday', max_length=10),
        ),
        migrations.AlterField(
            model_name='requests',
            name='reason',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='requests',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
