# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-31 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180131_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requester',
            name='assigned_authoriser',
            field=models.IntegerField(null=True),
        ),
    ]
