# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_requests_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='reason',
            field=models.TextField(max_length=200),
        ),
    ]
