# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20171107_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='document',
        ),
        migrations.AddField(
            model_name='requests',
            name='attachment',
            field=models.FileField(default='No file uploaded.', upload_to=home.models.user_directory_path),
        ),
    ]
