# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-31 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180131_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requester',
            name='assigned_authoriser',
            field=models.IntegerField(choices=[(2, 'test1'), (6, 'name4'), (7, 'test5'), (10, 'test7'), (11, 'test8'), (14, 'test10'), (16, 'hello1'), (29, 'zbvc382')], null=True),
        ),
    ]
