# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-03 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180303_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
