# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-07 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='attachment',
            field=models.CharField(default='', max_length=200),
        ),
    ]
