# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-07 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_template_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='template_name',
            field=models.CharField(max_length=40),
        ),
    ]
