# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-07 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import home.models
import home.validators


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20180307_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='attachment',
            field=models.FileField(null=True, upload_to=home.models.user_directory_path, validators=[home.validators.validate_file_size]),
        ),
    ]
