# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-08 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20180307_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarRestrictionPrivate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('description', models.CharField(default='', max_length=250)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Requester')),
            ],
        ),
    ]
