# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-08 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20180308_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarrestriction',
            old_name='description',
            new_name='reason',
        ),
    ]
