# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-08 23:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20180308_2223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CalendarRestriction',
            new_name='Restriction',
        ),
    ]
