# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-09 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20180308_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restriction',
            name='reason',
            field=models.TextField(max_length=500),
        ),
    ]
