# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-29 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_roles',
            new_name='user_role',
        ),
    ]
