# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-29 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180129_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Requester'), (2, 'Authoriser')], default=1),
        ),
    ]
