# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-18 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import home.models
import home.validators


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180211_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='attachment',
            field=models.FileField(null=True, upload_to=home.models.user_directory_path, validators=[home.validators.validate_file_size]),
        ),
    ]
