# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-04 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20180303_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='comment',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='request',
            name='reason',
            field=models.TextField(max_length=500),
        ),
    ]
