# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-11 17:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
