# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-12 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20180311_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
