# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-13 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20180312_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='leave_type',
            field=models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Compassionate Leave', 'Compassionate Leave'), ('Dependant Leave', 'Dependant Leave'), ('Parental Leave', 'Parental Leave'), ('Study Leave', 'Study Leave'), ('Other paid leave', 'Other paid leave'), ('Other unpaid leave', 'Other unpaid leave'), ('Sabbatical Leave', 'Sabbatical Leave')], default='Sick Leave', max_length=40),
        ),
    ]
